@host = http://localhost:8090
@token = your-jwt-token-here

### Health Check
GET {{host}}/health

### Permisos - Listar
GET {{host}}/permiso
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1aWQiOiJfbWlxdWVsLndlaW1hbm5AZ21haWwuY29tIiwic3ViIjoibWlxdWVsLndlaW1hbm5AZ21haWwuY29tIiwiaWF0IjoxNzcwNjgxMDM0LCJleHAiOjE3NzA2ODE5MzR9.07mrm1Kdl6Y9i2mWcQA60P-pH1tvrb7y_hi-iLMcVD9t0hVRJeyVvvisNfoVkmrGsPP9yZ_NKvPWx35xPuAxCg

### Permisos - Crear
POST {{host}}/permiso
Content-Type: application/json

{
    "nombre": "LECTURA_REPORTES",
    "recurso": "REPORTES",
    "accion": "LEER"
}

### Roles - Listar
GET {{host}}/rol

### Roles - Obtener por ID
GET {{host}}/rol/ssss

### Roles - Crear
POST {{host}}/rol
Content-Type: application/json

{
    "nombre": "ADMINISTRADOR",
    "descripcion": "Rol con todos los permisos",
    "permisos": [1]
}

### Roles - Actualizar
PUT {{host}}/rol/1
Content-Type: application/json

{
    "nombre": "ADMIN_MODIFICADO",
    "descripcion": "Rol actualizado",
    "permisos": [1]
}

### Roles - Eliminar
DELETE {{host}}/rol/1

### Usuarios - Listar
GET {{host}}/usuario

### Usuarios - Obtener por ID
GET {{host}}/usuario/1

### Usuarios - Crear
POST {{host}}/usuario
Content-Type: application/json

{
    "correo": "testd@example.com",
    "password": "passworD1!",
    "nombres": "Juand",
    "apellidos": "Perez",
    "fechaNacimiento": "05/05/1990",
    "genero": "Masculino",
    "telefono": "123456789",
    "direccion": "Calle Falsa 123",
    "nacionalidad": "Boliviana",
    "roles": [1]
}

### Usuarios - Actualizar
PUT {{host}}/usuario/1
Content-Type: application/json

{
    "correo": "juan.perez@newmail.com",
    "password": "NewPassword123!",
    "nombres": "Juan Carlos",
    "apellidos": "Perez Lopez",
    "fechaNacimiento": "15/05/1990",
    "genero": "Masculino",
    "telefono": "987654321",
    "direccion": "Av. Principal 456",
    "nacionalidad": "Boliviana",
    "roles": [1]
}

### Usuarios - Eliminar
DELETE {{host}}/usuario/1

### Auth - Login (Successful) @name login
POST {{host}}/login
Content-Type: application/json

{
    "username": "corina.collins@gmail.com",
    "password": "123456"
}

### Auth - Refresh Token (Invalid Token)
POST {{host}}/login/refresh-token
Authentication: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1aWQiOiJfdGVzdGRAZXhhbXBsZS5jb20iLCJzdWIiOiJ0ZXN0ZEBleGFtcGxlLmNvbSIsImlhdCI6MTc3MDI1MTcxNywiZXhwIjoxNzcwODU2NTE3fQ.QvMBcLhPJyLL6BWsnZKKv20sKCj9_AdGwOHybDix4SJ6xLFhTGmWIWQ86wnusGmNgOqoPTZgo7u8Xlyw3w0vdA

### Productos - Listar con Paginación
GET {{host}}/productos/paginacion?pageSize=10&pageNumber=0&sortField=id&sortOrder=ASC&almacenId=2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1aWQiOiJfZXVnZW5pYS5lcm5zZXJAaG90bWFpbC5jb20iLCJzdWIiOiJldWdlbmlhLmVybnNlckBob3RtYWlsLmNvbSIsImlhdCI6MTc3NDQ4Njg2MSwiZXhwIjoxNzc0NDg3NzYxfQ.QyDUItQUeyQC8um_gD8Mcrclvc7Tduv6wH5yt-ZDTskKk5DZDiNwIxFdEEk6CY68ZIh3DR7uCQzveof2D1cHvQ

### Productos - almacen
GET {{host}}/productos/almacen/4
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1aWQiOiJfdG9yaS5kaWNraW5zb25AeWFob28uY29tIiwic3ViIjoidG9yaS5kaWNraW5zb25AeWFob28uY29tIiwiaWF0IjoxNzc0ODM3ODk1LCJleHAiOjE3NzQ4Mzg3OTV9.sw0-REMA0ZPE0IjpChoziguuuxoKfNVO9SuRKWY5hhynQEofJHcRNu2YmDLycBlutJeG6EIYCkn2OXpBQ6RBbg

### Productos - Crear
POST {{host}}/producto
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1aWQiOiJfbWlxdWVsLndlaW1hbm5AZ21haWwuY29tIiwic3ViIjoibWlxdWVsLndlaW1hbm5AZ21haWwuY29tIiwiaWF0IjoxNzcwNjgxMDM0LCJleHAiOjE3NzA2ODE5MzR9.07mrm1Kdl6Y9i2mWcQA60P-pH1tvrb7y_hi-iLMcVD9t0hVRJeyVvvisNfoVkmrGsPP9yZ_NKvPWx35xPuAxCg

{
    "nombre": "Laptop HP",
    "descripcion": "Laptop de 15 pulgadas con procesador Intel i7",
    "marca": "LP-HP-001",
    "categoriaId": 1,
    "precioVentaActual": 1200.50,
    "unidadMedida": "Unidad"
}

### Nota - Crear
POST {{host}}/notas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1aWQiOiJfY29yaW5hLmNvbGxpbnNAZ21haWwuY29tIiwic3ViIjoiY29yaW5hLmNvbGxpbnNAZ21haWwuY29tIiwiaWF0IjoxNzc1MDE0NTcwLCJleHAiOjE3NzUwMTU0NzB9.n3sYICOace31LYlw9-6Gbxfaaz5B_UVjnQ7uvyg4ZzXj8cwqymcnWKh9vwSLWcX74sQSF3HeZwnDT3y-2K_xkw

{
    "tipoNota": "Compra",
    "numeroNota": "NOTA-001",
    "observaciones": "Compra de productos electrónicos",
    "moneda": "BOB",
    "usuarioId": 1,
    "clienteProveedorId": 1,
    "movimientos": [
        {
            "productoId": 7,
            "almacenId": 28,
            "cantidad": 5,
            "precioUnitarioCompra": 1200.50,
            "precioUnitarioVenta": 1500.00,
            "observaciones": "dsadsadsadsad"
        }
    ]
}

### Clientes Proveedores - Listar
GET {{host}}/notas/cliente-proveedor
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJ1aWQiOiJfdG9yaS5kaWNraW5zb25AeWFob28uY29tIiwic3ViIjoidG9yaS5kaWNraW5zb25AeWFob28uY29tIiwiaWF0IjoxNzc0ODM3ODk1LCJleHAiOjE3NzQ4Mzg3OTV9.sw0-REMA0ZPE0IjpChoziguuuxoKfNVO9SuRKWY5hhynQEofJHcRNu2YmDLycBlutJeG6EIYCkn2OXpBQ6RBbg
