// <auto-generated />
using System;
using ComprasVentas.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ComprasVentas.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260219023955_CompletedApp")]
    partial class CompletedApp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ComprasVentas.Models.Almacen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Codigo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("SucursalId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.ToTable("Almacenes");
                });

            modelBuilder.Entity("ComprasVentas.Models.AlmacenProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AlmacenId")
                        .HasColumnType("integer");

                    b.Property<int>("CantidadActual")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlmacenId");

                    b.HasIndex("ProductoId");

                    b.ToTable("AlmacenProductos");
                });

            modelBuilder.Entity("ComprasVentas.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ComprasVentas.Models.ClienteProveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("NroIdentificacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("ClienteProveedor");
                });

            modelBuilder.Entity("ComprasVentas.Models.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlmacenId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("numeric");

                    b.Property<int>("NotaId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("PrecioUnitarioCompra")
                        .HasPrecision(13, 2)
                        .HasColumnType("numeric(13,2)");

                    b.Property<decimal>("PrecioUnitarioVenta")
                        .HasPrecision(13, 2)
                        .HasColumnType("numeric(13,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("AlmacenId");

                    b.HasIndex("NotaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("ComprasVentas.Models.Nota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteProveedorId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Descuentos")
                        .HasPrecision(13, 2)
                        .HasColumnType("numeric(13,2)");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Impuestos")
                        .HasPrecision(13, 2)
                        .HasColumnType("numeric(13,2)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TipoNota")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("Total")
                        .HasPrecision(13, 2)
                        .HasColumnType("numeric(13,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClienteProveedorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("ComprasVentas.Models.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Recurso")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Permisos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Accion = "CREATE",
                            Nombre = "ROL_CREATE",
                            Recurso = "ROL"
                        },
                        new
                        {
                            Id = 2,
                            Accion = "READ",
                            Nombre = "ROL_READ",
                            Recurso = "ROL"
                        },
                        new
                        {
                            Id = 3,
                            Accion = "UPDATE",
                            Nombre = "ROL_UPDATE",
                            Recurso = "ROL"
                        },
                        new
                        {
                            Id = 4,
                            Accion = "DELETE",
                            Nombre = "ROL_DELETE",
                            Recurso = "ROL"
                        },
                        new
                        {
                            Id = 5,
                            Accion = "CREATE",
                            Nombre = "USUARIO_CREATE",
                            Recurso = "USUARIO"
                        },
                        new
                        {
                            Id = 6,
                            Accion = "READ",
                            Nombre = "USUARIO_READ",
                            Recurso = "USUARIO"
                        },
                        new
                        {
                            Id = 7,
                            Accion = "UPDATE",
                            Nombre = "USUARIO_UPDATE",
                            Recurso = "USUARIO"
                        },
                        new
                        {
                            Id = 8,
                            Accion = "DELETE",
                            Nombre = "USUARIO_DELETE",
                            Recurso = "USUARIO"
                        },
                        new
                        {
                            Id = 9,
                            Accion = "CREATE",
                            Nombre = "PERSONA_CREATE",
                            Recurso = "PERSONA"
                        },
                        new
                        {
                            Id = 10,
                            Accion = "READ",
                            Nombre = "PERSONA_READ",
                            Recurso = "PERSONA"
                        },
                        new
                        {
                            Id = 11,
                            Accion = "UPDATE",
                            Nombre = "PERSONA_UPDATE",
                            Recurso = "PERSONA"
                        },
                        new
                        {
                            Id = 12,
                            Accion = "DELETE",
                            Nombre = "PERSONA_DELETE",
                            Recurso = "PERSONA"
                        },
                        new
                        {
                            Id = 13,
                            Accion = "CREATE",
                            Nombre = "PERMISO_CREATE",
                            Recurso = "PERMISO"
                        },
                        new
                        {
                            Id = 14,
                            Accion = "READ",
                            Nombre = "PERMISO_READ",
                            Recurso = "PERMISO"
                        },
                        new
                        {
                            Id = 15,
                            Accion = "UPDATE",
                            Nombre = "PERMISO_UPDATE",
                            Recurso = "PERMISO"
                        },
                        new
                        {
                            Id = 16,
                            Accion = "DELETE",
                            Nombre = "PERMISO_DELETE",
                            Recurso = "PERMISO"
                        },
                        new
                        {
                            Id = 17,
                            Accion = "READ",
                            Nombre = "DASHBOARD_READ",
                            Recurso = "DASHBOARD"
                        });
                });

            modelBuilder.Entity("ComprasVentas.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Genero")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellidos = "Pérez",
                            Direccion = "Calle Principal 123",
                            FechaNacimiento = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Genero = "Masculino",
                            Nacionalidad = "Mexicana",
                            Nombres = "Juan",
                            Telefono = "+1234567890"
                        },
                        new
                        {
                            Id = 2,
                            Apellidos = "González",
                            Direccion = "Avenida Central 456",
                            FechaNacimiento = new DateTime(1990, 8, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Genero = "Femenino",
                            Nacionalidad = "Mexicana",
                            Nombres = "María",
                            Telefono = "+9876543210"
                        },
                        new
                        {
                            Id = 3,
                            Apellidos = "López",
                            Direccion = "Plaza Mayor 789",
                            FechaNacimiento = new DateTime(1995, 3, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Genero = "Masculino",
                            Nacionalidad = "Mexicana",
                            Nombres = "Carlos",
                            Telefono = "+1122334455"
                        });
                });

            modelBuilder.Entity("ComprasVentas.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean");

                    b.Property<string>("Imagen")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Marca")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PrecioVentaActual")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("UnidadMedida")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("ComprasVentas.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Revoked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ComprasVentas.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Acceso completo a todos los recursos del sistema",
                            Nombre = "Super Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Administración del sistema (sin permisos de super administrador)",
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Usuario regular del sistema con permisos limitados",
                            Nombre = "Usuario"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Usuario con acceso de solo lectura",
                            Nombre = "Invitado"
                        });
                });

            modelBuilder.Entity("ComprasVentas.Models.Sucursal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("ComprasVentas.Models.SucursalUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SucursalId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SucursalId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("SucursalUsers");
                });

            modelBuilder.Entity("ComprasVentas.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Correo = "superadmin@comprasventas.com",
                            Nombre = "superadmin",
                            Password = "$2a$11$JvrSYkK8p.kpqsW5BoyIweIdDgJJGm6r0nL9.Qd/fYHB85pLuBGhy"
                        },
                        new
                        {
                            Id = 2,
                            Correo = "admin@comprasventas.com",
                            Nombre = "admin",
                            Password = "$2a$11$GfnhbgoQRmPxVhOAhigSQOeXyoccrmPDTKnA3N1RszFvQQpbi4niK"
                        },
                        new
                        {
                            Id = 3,
                            Correo = "usuario1@comprasventas.com",
                            Nombre = "usuario1",
                            Password = "$2a$11$cWGKiuqlX3PriTe15fYODOMHE/C26X8GxPxx4gylTnkl6uHfYtj/e"
                        });
                });

            modelBuilder.Entity("permiso_rol", b =>
                {
                    b.Property<int>("PermisosId")
                        .HasColumnType("integer");

                    b.Property<int>("RolesId")
                        .HasColumnType("integer");

                    b.HasKey("PermisosId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("permiso_rol", (string)null);

                    b.HasData(
                        new
                        {
                            PermisosId = 1,
                            RolesId = 1
                        },
                        new
                        {
                            PermisosId = 2,
                            RolesId = 1
                        },
                        new
                        {
                            PermisosId = 3,
                            RolesId = 1
                        },
                        new
                        {
                            PermisosId = 4,
                            RolesId = 1
                        },
                        new
                        {
                            PermisosId = 5,
                            RolesId = 1
                        },
                        new
                        {
                            PermisosId = 6,
                            RolesId = 1
                        },
                        new
                        {
                            PermisosId = 7,
                            RolesId = 1
                        },
                        new
                        {
                            PermisosId = 8,
                            RolesId = 1
                        },
                        new
                        {
                            PermisosId = 9,
                            RolesId = 1
                        },
                        new
                        {
                            PermisosId = 10,
                            RolesId = 1
                        },
                        new
                        {
                            PermisosId = 11,
                            RolesId = 1
                        },
                        new
                        {
                            PermisosId = 12,
                            RolesId = 1
                        },
                        new
                        {
                            PermisosId = 13,
                            RolesId = 1
                        },
                        new
                        {
                            PermisosId = 14,
                            RolesId = 1
                        },
                        new
                        {
                            PermisosId = 15,
                            RolesId = 1
                        },
                        new
                        {
                            PermisosId = 16,
                            RolesId = 1
                        },
                        new
                        {
                            PermisosId = 17,
                            RolesId = 1
                        },
                        new
                        {
                            PermisosId = 1,
                            RolesId = 2
                        },
                        new
                        {
                            PermisosId = 2,
                            RolesId = 2
                        },
                        new
                        {
                            PermisosId = 3,
                            RolesId = 2
                        },
                        new
                        {
                            PermisosId = 4,
                            RolesId = 2
                        },
                        new
                        {
                            PermisosId = 5,
                            RolesId = 2
                        },
                        new
                        {
                            PermisosId = 6,
                            RolesId = 2
                        },
                        new
                        {
                            PermisosId = 7,
                            RolesId = 2
                        },
                        new
                        {
                            PermisosId = 8,
                            RolesId = 2
                        },
                        new
                        {
                            PermisosId = 9,
                            RolesId = 2
                        },
                        new
                        {
                            PermisosId = 10,
                            RolesId = 2
                        },
                        new
                        {
                            PermisosId = 11,
                            RolesId = 2
                        },
                        new
                        {
                            PermisosId = 12,
                            RolesId = 2
                        },
                        new
                        {
                            PermisosId = 17,
                            RolesId = 2
                        },
                        new
                        {
                            PermisosId = 6,
                            RolesId = 3
                        },
                        new
                        {
                            PermisosId = 7,
                            RolesId = 3
                        },
                        new
                        {
                            PermisosId = 10,
                            RolesId = 3
                        },
                        new
                        {
                            PermisosId = 11,
                            RolesId = 3
                        },
                        new
                        {
                            PermisosId = 17,
                            RolesId = 3
                        },
                        new
                        {
                            PermisosId = 2,
                            RolesId = 4
                        },
                        new
                        {
                            PermisosId = 6,
                            RolesId = 4
                        },
                        new
                        {
                            PermisosId = 10,
                            RolesId = 4
                        });
                });

            modelBuilder.Entity("usuario_rol", b =>
                {
                    b.Property<int>("UsuariosId")
                        .HasColumnType("integer");

                    b.Property<int>("RolesId")
                        .HasColumnType("integer");

                    b.HasKey("UsuariosId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("usuario_rol", (string)null);

                    b.HasData(
                        new
                        {
                            UsuariosId = 1,
                            RolesId = 1
                        },
                        new
                        {
                            UsuariosId = 2,
                            RolesId = 2
                        },
                        new
                        {
                            UsuariosId = 3,
                            RolesId = 3
                        });
                });

            modelBuilder.Entity("ComprasVentas.Models.Almacen", b =>
                {
                    b.HasOne("ComprasVentas.Models.Sucursal", "Sucursal")
                        .WithMany("Almacenes")
                        .HasForeignKey("SucursalId");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("ComprasVentas.Models.AlmacenProducto", b =>
                {
                    b.HasOne("ComprasVentas.Models.Almacen", "Almacen")
                        .WithMany("AlmacenProductos")
                        .HasForeignKey("AlmacenId");

                    b.HasOne("ComprasVentas.Models.Producto", "Producto")
                        .WithMany("AlmacenProductos")
                        .HasForeignKey("ProductoId");

                    b.Navigation("Almacen");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ComprasVentas.Models.Movimiento", b =>
                {
                    b.HasOne("ComprasVentas.Models.Almacen", "Almacen")
                        .WithMany("Movimientos")
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComprasVentas.Models.Nota", "Nota")
                        .WithMany("Movimientos")
                        .HasForeignKey("NotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComprasVentas.Models.Producto", "Producto")
                        .WithMany("Movimientos")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Almacen");

                    b.Navigation("Nota");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ComprasVentas.Models.Nota", b =>
                {
                    b.HasOne("ComprasVentas.Models.ClienteProveedor", "ClienteProveedor")
                        .WithMany("Notas")
                        .HasForeignKey("ClienteProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComprasVentas.Models.Usuario", "Usuario")
                        .WithMany("Notas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClienteProveedor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ComprasVentas.Models.Persona", b =>
                {
                    b.HasOne("ComprasVentas.Models.Usuario", "Usuario")
                        .WithOne("Persona")
                        .HasForeignKey("ComprasVentas.Models.Persona", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ComprasVentas.Models.Producto", b =>
                {
                    b.HasOne("ComprasVentas.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ComprasVentas.Models.RefreshToken", b =>
                {
                    b.HasOne("ComprasVentas.Models.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ComprasVentas.Models.SucursalUser", b =>
                {
                    b.HasOne("ComprasVentas.Models.Sucursal", "Sucursal")
                        .WithMany("SucursalUsers")
                        .HasForeignKey("SucursalId");

                    b.HasOne("ComprasVentas.Models.Usuario", "Usuario")
                        .WithMany("SucursalUsers")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Sucursal");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("permiso_rol", b =>
                {
                    b.HasOne("ComprasVentas.Models.Permiso", null)
                        .WithMany()
                        .HasForeignKey("PermisosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComprasVentas.Models.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("usuario_rol", b =>
                {
                    b.HasOne("ComprasVentas.Models.Rol", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComprasVentas.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComprasVentas.Models.Almacen", b =>
                {
                    b.Navigation("AlmacenProductos");

                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("ComprasVentas.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ComprasVentas.Models.ClienteProveedor", b =>
                {
                    b.Navigation("Notas");
                });

            modelBuilder.Entity("ComprasVentas.Models.Nota", b =>
                {
                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("ComprasVentas.Models.Producto", b =>
                {
                    b.Navigation("AlmacenProductos");

                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("ComprasVentas.Models.Sucursal", b =>
                {
                    b.Navigation("Almacenes");

                    b.Navigation("SucursalUsers");
                });

            modelBuilder.Entity("ComprasVentas.Models.Usuario", b =>
                {
                    b.Navigation("Notas");

                    b.Navigation("Persona");

                    b.Navigation("RefreshTokens");

                    b.Navigation("SucursalUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
